# Travis CI config for Limba
# unattended full upgrade: sudo apt-get -o Dpkg::Options::="--force-confold" --force-yes -fuy dist-upgrade

language: c

compiler:
  - gcc
  - clang
before_script:
  - env | sort
  - uname -m && uname -r
script:
  - mkdir build && cd build
  - cmake -DMAINTAINER=ON -DLIBUILD=ON ..
  - make && make install DESTDIR=./install_root/ && sudo make test ARGS=-V
